package BehaviorNet;

import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;
import simView.*;
import java.awt.*;

public class BehaviorNet extends ViewableDigraph{


public BehaviorNet(){ this("BehaviorNet");  }

int numOfBehavior = configData.numOfBehavior;
int i,j;

public BehaviorNet(String nm){
  super(nm);

  Behavior[] behavior = new Behavior[numOfBehavior];

  behavior[0] = new behavior_Rest("REST");
  behavior[1] = new behavior_Escape("ESCAPE");
  behavior[2] = new behavior_Retreat("RETREAT");
  behavior[3] = new behavior_Defense("DEFENSE");
  behavior[4] = new behavior_Hide("HIDE");
  behavior[5] = new behavior_Eat("EAT");
  behavior[6] = new behavior_Forage("FORAGE");
  behavior[7] = new behavior_Swim("SWIM");
  for(i=0;i<numOfBehavior;i++){  // add the behavior models
    add(behavior[i]);
  }

  winnerTakeAll wta = new winnerTakeAll();
  add(wta);

  Action A_eat = new action_Eat("action_Eat");
  Action A_move = new action_Move("action_Move");
  add(A_eat);
  add(A_move);

  for(i=0;i<numOfBehavior;i++){  //add couplings
    for(j=0;j<numOfBehavior;j++){
      if(j!=i){
        addCoupling(behavior[i],"inhib_out",behavior[j],"inhibitions");
      }
    }
    addCoupling(behavior[i],"my_excit",wta,"in");
    addCoupling(wta,"out"+i,behavior[i],"selected");
    //----------------------------------
    if(behavior[i].getName()=="EAT")
      addCoupling(behavior[i],"commd_out",A_eat,"In");
    else
      addCoupling(behavior[i],"commd_out",A_move,"In");

  }


}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(747, 450);
        ((ViewableComponent)withName("FORAGE")).setPreferredLocation(new Point(412, 91));
        ((ViewableComponent)withName("EAT")).setPreferredLocation(new Point(-3, 96));
        ((ViewableComponent)withName("action_Eat")).setPreferredLocation(new Point(355, 363));
        ((ViewableComponent)withName("RETREAT")).setPreferredLocation(new Point(-2, 21));
        ((ViewableComponent)withName("ESCAPE")).setPreferredLocation(new Point(414, 172));
        ((ViewableComponent)withName("winnerTakeAll")).setPreferredLocation(new Point(238, 101));
        ((ViewableComponent)withName("action_Move")).setPreferredLocation(new Point(184, 361));
        ((ViewableComponent)withName("REST")).setPreferredLocation(new Point(410, 14));
        ((ViewableComponent)withName("HIDE")).setPreferredLocation(new Point(-2, 179));
        ((ViewableComponent)withName("SWIM")).setPreferredLocation(new Point(415, 255));
        ((ViewableComponent)withName("DEFENSE")).setPreferredLocation(new Point(-1, 263));
    }
}
