package BehaviorNet;

import genDevs.modeling.*;
import genDevs.simulation.*;
import simView.*;
import GenCol.*;
import java.util.*;
import java.awt.*;

public class crayfishSys extends ViewableDigraph{//digraph{

  public crayfishSys(){
    this("crayfishSys");
  }

public crayfishSys(String nm){
super(nm);

Environment env = new Environment("Environment");
add(env);

EnvInterface envI = new EnvInterface("EnvInterface");
add(envI);
envI.setHidden(true);

centralRepository cRps = new centralRepository("centralRepository");
add(cRps);
cRps.setHidden(true);


    Crayfish crayF = new Crayfish("crayfish");
    add(crayF);

    //crayF.setBlackBox(true);

    Predator pred = new Predator("predator");
    add(pred);
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(807, 421);
        ((ViewableComponent)withName("Environment")).setPreferredLocation(new Point(15, 44));
        ((ViewableComponent)withName("crayfish")).setPreferredLocation(new Point(67, 27));
        ((ViewableComponent)withName("predator")).setPreferredLocation(new Point(8, 170));
    }
}
