package BehaviorNetwork;

import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;
import simView.*;
import java.awt.*;

public class BehaviorNet extends ViewableDigraph{


public BehaviorNet(){ this("BehaviorNet");  }

int numOfBehavior = configData.numOfBehavior;
int i,j;

public BehaviorNet(String nm){
  super(nm);

  Behavior[] behavior = new Behavior[numOfBehavior];

  behavior[0] = new behavior_Rest("REST");
  behavior[1] = new behavior_Escape("ESCAPE");
  behavior[2] = new behavior_Retreat("RETREAT");
  behavior[3] = new behavior_Defense("DEFENSE");
  behavior[4] = new behavior_Hide("HIDE");
  behavior[5] = new behavior_Eat("EAT");
  behavior[6] = new behavior_Forage("FORAGE");
  behavior[7] = new behavior_Swim("SWIM");

  winnerTakeAll wta = new winnerTakeAll();
  add(wta);

  for(i=0;i<numOfBehavior;i++){  // add the behavior models
    add(behavior[i]);
  }

  for(i=0;i<numOfBehavior;i++){  //add couplings
    for(j=0;j<numOfBehavior;j++){
      if(j!=i){
        addCoupling(behavior[i],"excitation",behavior[j],"inhibitions");
      }
    }
    addCoupling(behavior[i],"out",wta,"in");
    addCoupling(wta,"out"+i,behavior[i],"selected");
  }


}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(662, 335);
        ((ViewableComponent)withName("DEFENSE")).setPreferredLocation(new Point(-8, 262));
        ((ViewableComponent)withName("SWIM")).setPreferredLocation(new Point(415, 255));
        ((ViewableComponent)withName("RETREAT")).setPreferredLocation(new Point(5, 23));
        ((ViewableComponent)withName("winnerTakeAll")).setPreferredLocation(new Point(250, 131));
        ((ViewableComponent)withName("FORAGE")).setPreferredLocation(new Point(412, 91));
        ((ViewableComponent)withName("EAT")).setPreferredLocation(new Point(4, 96));
        ((ViewableComponent)withName("ESCAPE")).setPreferredLocation(new Point(414, 172));
        ((ViewableComponent)withName("HIDE")).setPreferredLocation(new Point(-2, 179));
        ((ViewableComponent)withName("REST")).setPreferredLocation(new Point(410, 14));
    }
}
